jvm_binary(name='distance_protobuf',
  dependencies=[
    'src/protobuf/com/twitter/common/examples/distance',
  ],
  source='DistanceProtobuf.java',
  main='com.twitter.common.examples.distance_protobuf.DistanceProtobuf',
)
