jvm_binary(name='trip_protobuf',
  dependencies=[
    'src/protobuf/com/twitter/common/examples/distance',
    'src/protobuf/com/twitter/common/examples/trip',
  ],
  source='TripProtobuf.java',
  main='com.twitter.common.examples.trip_protobuf.TripProtobuf',
)
