jvm_binary(
  name = 'distance-protobuf-example',
  source = './src/main/java/com/squareup/zundel/hello/DistanceProtobuf.java',
  dependencies = [
    'zundel-hello/distance/src/main/protobuf/squareup/zundel/hello/distance',
  ],
  main = 'com.squareup.zundel.hello.DistanceProtobuf',
)
